CREATE TABLE FINAL_TAB
(
  JOB_REC                VARCHAR2(20),
  DATA                   VARCHAR2(2000),
  DLR_REF_TABLES         VARCHAR2(2000),
  NO_DLR_REF_TABLES      VARCHAR2(20),
  PP_TABLES              VARCHAR2(2000),
  NO_PP_TABLES           VARCHAR2(20),
  QA_TABLES              VARCHAR2(2000),
  NO_QA_TABLES           VARCHAR2(20),
  DEP_FUN_TABLES         VARCHAR2(2000),
  NO_DEP_FUN_TABLES      VARCHAR2(20),
  NBI_TABLES             VARCHAR2(2000),
  NO_NBI_TABLES          VARCHAR2(20),
  OTHER_TABLES           VARCHAR2(2000),
  NO_OTHER_TABLES        VARCHAR2(20),
  OPPAR_DB_REQUEST_FLAG  VARCHAR2(2),
  REQUEST_FLAG           VARCHAR2(20),
  UDATE                  VARCHAR2(20)
);
