set heading off
set verify off
set pages 1000;
define connection=&1;
select '***************************************************' from dual;
select substr(upper('&&connection'),1,3) from dual;
select 'SWITCH FLAG' from dual;

select 'DEALER TABLES' from dual;
set feedback on
select 
	REFTABLENAME,ACTIVESNAPSHOT,SWITCHFLAG
from 
	&connection.active_snapshot
where 
	SWITCHFLAG='Y' 
and    
        REFTABLENAME in ('COM_AGREEMENT','COMMITMENT_TERMS_DESC','COM_COMMITMENT_TERMS','COM_DLR_AGREEMENT','COM_PAYMENT_GROUP','COM_RAMP_DETAILS','COM_RAMP_GROUP','COM_RED_BONUS_RAMP','COM_REL_DATE_BONUS','COM_RETAIN_DETAIL','COM_SOC_SPA','DC_GL_ACCOUNT','DEALER_ADDITIONAL_COM','DEALER_POLICY','DEALER_QTA','DLR_ADJ_RSN','DLR_COM_SOC_SPA','DLR_SUBSCRIBER_ELIG','EQUIPMENT_SKU','EQU_AGREEMENT','EQU_COMMIT_TERM_RAMP','EQU_DLR_AGREEMENT','EQU_PAYMENT_GROUP','EQU_RETAIN_DETAIL','RES_DLR_MINI_ELIG_PARAMS','SKU_GP_DSC','SKU_GROUP','MANUFACTURER_SPA','MODEL_SPA','PROMO_AGREEMENT','PROMO_DLR_AGREEMENT','PROMO_RAMP_DETAILS','REN_DLR_AGREEMENT','REN_UPG_AGREEMENT','REN_UPG_GRID','RES_AGREEMENT','RES_CHURN_BONUS','RES_COMMITMENT_TERMS','RES_CRT_CHURN','RES_DLR_AGREEMENT','RES_PAYMENT_GROUP','RES_PER_COUNT_RAMP','RES_RAMP_GROUP','RES_RED_BONUS','RES_SUB_ACTV_DATE','RES_SUB_AVERA_RAMP','RES_SUB_COMB','RES_SUB_COUNT_RAMP','RES_SUB_RVN','RES_SUB_SRV_LGTH','SOC_GP_DSC','SOC_GROUP','SUB_MARKE!
 T_SEC','TYPE_SPA')
order by 
        REFTABLENAME;

set feedback off
select 'PRICEPLAN TABLES' from dual;
set feedback on
select 
	REFTABLENAME,ACTIVESNAPSHOT,SWITCHFLAG
from 
	&connection.active_snapshot
where   
	SWITCHFLAG='Y'
and
	REFTABLENAME in ('SOC_MAPPING','CATEGORIES_DETAILS','PP_CATEGORIES','CALLING_ROUTE_CONTROL','DISCOUNT_CATEGORY','DISCOUNT_PLAN','DISCOUNT_SALE_CHANNEL','DISCOUNT_TIER','DOMESTIC_AREA_IND','FEATURE','FEATURE_CALLING_ROUTE','FM_RELATED_FTR','INCLUS_BY_PERIOD','MOU_BY_PERIOD','PERIOD','PERIOD_NAME','PERIOD_NAME_LANG','PERIOD_SET','PP_AC_RATE','PP_COMMITMENT','PP_OC_RATE','PP_PROMO_TERMS','PP_RC_RATE','PP_REMARK','PP_UC_RATE','PRODUCT','PROMOTION_TERMS','RATED_FEATURE','SOC','SOC_RELATION','SOC_SALE_CHANNEL','SOC_SUB_MARKET','SPECIAL_DAYS','SPECIAL_DAYS_SET','TIER','UC_RATED_FEATURE','SOC_ACC_TYPE_EXCL','INTL_SOC_CATEGORY','SOC_INTNL_TOLL','PP_VIEW','PROMO_VIEW','OPTIONAL_VIEW','CONTRACT_MAPPING_SOC','PROMO_TYPE','PROMO_TYPE_PERIOD','RETIRING_GROUP_PP','PRTNR_ADJ_RSN_CHRG','DISCOUNT_SOC','SOC_CATEGORIES_LINK','DISCOUNT_SUB_MARKET','DYNAMIC_SOC_MAPPING','DYNAMIC_SOC_MAPPING_LINK','ELIG_PP','ELIGIBILITY_DECISION','FLEXIBLE_ETF')
order by
	REFTABLENAME;

set feedback off
select 'OTHER TABLES' from dual;
set feedback on
select
       REFTABLENAME,ACTIVESNAPSHOT,SWITCHFLAG
from
       &connection.active_snapshot
where
       SWITCHFLAG='Y'
and 
      REFTABLENAME not in ('SOC_MAPPING','SOC_CATEGORIES_LINK','CATEGORIES_DETAILS','PP_CATEGORIES','COM_AGREEMENT','COMMITMENT_TERMS_DESC','COM_COMMITMENT_TERMS','COM_DLR_AGREEMENT','COM_PAYMENT_GROUP','COM_RAMP_DETAILS','COM_RAMP_GROUP','COM_RED_BONUS_RAMP','COM_REL_DATE_BONUS','COM_RETAIN_DETAIL','COM_SOC_SPA','DC_GL_ACCOUNT','DEALER_ADDITIONAL_COM','DEALER_POLICY','DEALER_QTA','DLR_ADJ_RSN','DLR_COM_SOC_SPA','DLR_SUBSCRIBER_ELIG','EQUIPMENT_SKU','EQU_AGREEMENT','EQU_COMMIT_TERM_RAMP','EQU_DLR_AGREEMENT','EQU_PAYMENT_GROUP','EQU_RETAIN_DETAIL','RES_DLR_MINI_ELIG_PARAMS','SKU_GP_DSC','SKU_GROUP','MANUFACTURER_SPA','MODEL_SPA','PROMO_AGREEMENT','PROMO_DLR_AGREEMENT','PROMO_RAMP_DETAILS','REN_DLR_AGREEMENT','REN_UPG_AGREEMENT','REN_UPG_GRID','RES_AGREEMENT','RES_CHURN_BONUS','RES_COMMITMENT_TERMS','RES_CRT_CHURN','RES_DLR_AGREEMENT','RES_PAYMENT_GROUP','RES_PER_COUNT_RAMP','DISCOUNT_SOC','RES_RAMP_GROUP','RES_RED_BONUS','RES_SUB_ACTV_DATE','RES_SUB_AVERA_RAMP','RES_SUB_COMB','RES_SUB_COUNT_RAMP','RES_SUB_RVN','RES_SUB_SRV_LGTH','SOC_GP_DSC','SOC_GROUP','SUB_MARKET_SEC','TYPE_SPA','CALLING_ROUTE_CONTROL','DISCOUNT_CATEGORY','DISCOUNT_PLAN','DISCOUNT_SALE_CHANNEL','DISCOUNT_TIER','DOMESTIC_AREA_IND','FEATURE','FEATURE_CALLING_ROUTE','FM_RELATED_FTR','INCLUS_BY_PERIOD','MOU_BY_PERIOD','PERIOD','PERIOD_NAME','PERIOD_NAME_LANG','PERIOD_SET','PP_AC_RATE','PP_COMMITMENT','PP_OC_RATE','PP_PROMO_TERMS','PP_RC_RATE','PP_REMARK','PP_UC_RATE','PRODUCT','PROMOTION_TERMS','RATED_FEATURE','SOC','SOC_RELATION','SOC_SALE_CHANNEL','SOC_SUB_MARKET','SPECIAL_DAYS','SPECIAL_DAYS_SET','TIER','UC_RATED_FEATURE','SOC_ACC_TYPE_EXCL','INTL_SOC_CATEGORY','SOC_INTNL_TOLL','PP_VIEW','PROMO_VIEW','OPTIONAL_VIEW','CONTRACT_MAPPING_SOC','PROMO_TYPE','PROMO_TYPE_PERIOD','RETIRING_GROUP_PP','PRTNR_ADJ_RSN_CHRG','SOC_CATEGORIES_LINK','DISCOUNT_SUB_MARKET','DYNAMIC_SOC_MAPPING','DYNAMIC_SOC_MAPPING_LINK','ELIG_PP','ELIGIBILITY_DECISION','FLEXIBLE_ETF')
order by
        REFTABLENAME;

set feedback off
select '***************************************************' from dual;
exit;

